### ISSUE TITLE
Optional Capcodes

### ISSUE THREAD

**Issue by Smartie90** [cyberjunky/home-assistant-p2000#4] opened 2020-01-11 16:47 UTC
Hi,

I'm working with the optional capcode option but it's not working. I try too find the problem but i'm realy new in phyton. could you help me with the code.

**Comment by Smartie90** [comment] 2020-01-21 18:41
Hey,
I have read your code and think it will go wrong in the last part. the variable "msgtext" is used to indicate whether the message is passing through the distance filter. when the message passes through this filter, it is always published. In my opinion, these variables should be emptied in the last piece if it does not pass through the capcode filter. is this correct?

something like:
`                        if 'summary' in item:
                            capcodetext = item.summary.replace("<br />", "\n")

                            if capcodes:
                                for capcode in capcodes:
                                    _LOGGER.debug("Searching for capcode %s in %s", capcode.strip(), capcodetext)
                                    if (capcodetext.find(capcode) != -1):
                                        _LOGGER.debug("Found capcode %s", capcode)
                                    else:
										msgtext = ''
										_LOGGER.debug("Didn't find capcode %s, skip.", capcode)
                                        continue`

**Comment by cyberjunky** [comment] 2020-01-21 19:37
You could be right indeed, testing with it now.

**Comment by Smartie90** [comment] 2020-01-25 09:22
for me it's working

**Comment by cyberjunky** [comment] 2020-01-25 14:05
That's good news, did it also fix the lat/long being 0,0 on many messages?

**Comment by rodeho** [comment] 2020-02-24 18:19
Guys I'm new to homeassistant, as firefighter I hope to switch on my home HUE lights when the alarm sounds. 

It seems to be working fine with the radius setting. But I'm not receiving messages with the capcode feature, I'm not receiving any alarm messages with the sensor when the capcodes: syntax is added?

Just noticed that the first 0 is not in the RSS feed log source, that could be a cause. Will let you know the test results.

Its unclear for me if "radius" is still mandatory when using only capcodes?

@cyberjunky is the fix from @Smartie90 already merged into the master?

sensor:
  - platform: p2000
    name: Utrecht
    regios: 9
    disciplines: 1
    radius: 150000
    scan_interval: 10
    capcodes: 0706001

**Comment by rodeho** [comment] 2020-02-24 19:29
sensor:
  - platform: p2000
    name: Utrecht
    regios: 9
    disciplines: 1,2,3,4
    radius: 150000
    scan_interval: 10
    capcodes: 706001, 1420999


19:50:50 24-02-20 | GROUP-1 | B1 AMBU 18186 Langeweg 3331LZ Zwijndrecht ZWIJND bon 25792
  | 1420999 | Meldkamer Rotterdam (Monitorcode)




`2020-02-24 19:50:24 DEBUG (MainThread) [custom_components.p2000.sensor] Fetch URL: https://feeds.livep2000.nl?r=9&d=1
2020-02-24 19:50:24 DEBUG (MainThread) [custom_components.p2000.sensor] Fetched data = {'bozo': False, 'entries': [], 'feed': {}, 'headers': {'server': 'nginx', 'date': 'Mon, 24 Feb 2020 18:50:24 GMT', 'connection': 'close', 'x-powered-by': 'Express', 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"'}, 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"', 'href': 'https://feeds.livep2000.nl?r=9&d=1', 'status': 304, 'version': '', 'debug_message': 'The feed has not changed since you last checked, so the server sent no data.  This is a feature, not a bug!'}
2020-02-24 19:50:24 DEBUG (MainThread) [custom_components.p2000.sensor] Fetch URL: https://feeds.livep2000.nl?r=9&d=1
2020-02-24 19:50:24 DEBUG (MainThread) [custom_components.p2000.sensor] Fetched data = {'bozo': False, 'entries': [], 'feed': {}, 'headers': {'server': 'nginx', 'date': 'Mon, 24 Feb 2020 18:50:24 GMT', 'connection': 'close', 'x-powered-by': 'Express', 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"'}, 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"', 'href': 'https://feeds.livep2000.nl?r=9&d=1', 'status': 304, 'version': '', 'debug_message': 'The feed has not changed since you last checked, so the server sent no data.  This is a feature, not a bug!'}
2020-02-24 19:50:30 INFO (MainThread) [hacs.factory] Task processing of 2 tasks completed in 9 seconds
2020-02-24 19:50:35 DEBUG (MainThread) [custom_components.p2000.sensor] Fetch URL: https://feeds.livep2000.nl?r=9&d=1
2020-02-24 19:50:35 DEBUG (MainThread) [custom_components.p2000.sensor] Fetched data = {'bozo': False, 'entries': [], 'feed': {}, 'headers': {'server': 'nginx', 'date': 'Mon, 24 Feb 2020 18:50:35 GMT', 'connection': 'close', 'x-powered-by': 'Express', 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"'}, 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"', 'href': 'https://feeds.livep2000.nl?r=9&d=1', 'status': 304, 'version': '', 'debug_message': 'The feed has not changed since you last checked, so the server sent no data.  This is a feature, not a bug!'}
2020-02-24 19:50:35 DEBUG (MainThread) [custom_components.p2000.sensor] Fetch URL: https://feeds.livep2000.nl?r=9&d=1
2020-02-24 19:50:35 DEBUG (MainThread) [custom_components.p2000.sensor] Fetched data = {'bozo': False, 'entries': [], 'feed': {}, 'headers': {'server': 'nginx', 'date': 'Mon, 24 Feb 2020 18:50:35 GMT', 'connection': 'close', 'x-powered-by': 'Express', 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"'}, 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"', 'href': 'https://feeds.livep2000.nl?r=9&d=1', 'status': 304, 'version': '', 'debug_message': 'The feed has not changed since you last checked, so the server sent no data.  This is a feature, not a bug!'}
2020-02-24 19:50:46 DEBUG (MainThread) [custom_components.p2000.sensor] Fetch URL: https://feeds.livep2000.nl?r=9&d=1
2020-02-24 19:50:46 DEBUG (MainThread) [custom_components.p2000.sensor] Fetched data = {'bozo': False, 'entries': [], 'feed': {}, 'headers': {'server': 'nginx', 'date': 'Mon, 24 Feb 2020 18:50:46 GMT', 'connection': 'close', 'x-powered-by': 'Express', 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"'}, 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"', 'href': 'https://feeds.livep2000.nl?r=9&d=1', 'status': 304, 'version': '', 'debug_message': 'The feed has not changed since you last checked, so the server sent no data.  This is a feature, not a bug!'}
2020-02-24 19:50:46 DEBUG (MainThread) [custom_components.p2000.sensor] Fetch URL: https://feeds.livep2000.nl?r=9&d=1
2020-02-24 19:50:46 DEBUG (MainThread) [custom_components.p2000.sensor] Fetched data = {'bozo': False, 'entries': [], 'feed': {}, 'headers': {'server': 'nginx', 'date': 'Mon, 24 Feb 2020 18:50:46 GMT', 'connection': 'close', 'x-powered-by': 'Express', 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"'}, 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"', 'href': 'https://feeds.livep2000.nl?r=9&d=1', 'status': 304, 'version': '', 'debug_message': 'The feed has not changed since you last checked, so the server sent no data.  This is a feature, not a bug!'}
2020-02-24 19:50:57 DEBUG (MainThread) [custom_components.p2000.sensor] Fetch URL: https://feeds.livep2000.nl?r=9&d=1
2020-02-24 19:50:57 DEBUG (MainThread) [custom_components.p2000.sensor] Fetched data = {'bozo': False, 'entries': [], 'feed': {}, 'headers': {'server': 'nginx', 'date': 'Mon, 24 Feb 2020 18:50:57 GMT', 'connection': 'close', 'x-powered-by': 'Express', 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"'}, 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"', 'href': 'https://feeds.livep2000.nl?r=9&d=1', 'status': 304, 'version': '', 'debug_message': 'The feed has not changed since you last checked, so the server sent no data.  This is a feature, not a bug!'}
2020-02-24 19:50:57 DEBUG (MainThread) [custom_components.p2000.sensor] Fetch URL: https://feeds.livep2000.nl?r=9&d=1
2020-02-24 19:50:57 DEBUG (MainThread) [custom_components.p2000.sensor] Fetched data = {'bozo': False, 'entries': [], 'feed': {}, 'headers': {'server': 'nginx', 'date': 'Mon, 24 Feb 2020 18:50:57 GMT', 'connection': 'close', 'x-powered-by': 'Express', 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"'}, 'etag': 'W/"75cb-4qPDEVetzRuo0PTBjkypwvwa8iI"', 'href': 'https://feeds.livep2000.nl?r=9&d=1', 'status': 304, 'version': '', 'debug_message': 'The feed has not changed since you last checked, so the server sent no data.  This is a feature, not a bug!'}`

**Comment by cyberjunky** [comment] 2020-02-25 07:25
Ja ik zal de docs duidelijker maken, in welke volgorde de filters werken.

**Closed by cyberjunky** 2020-02-25 07:25 UTC
